---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-json
          - id: check-xml

    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
          - id: black
    - repo: https://github.com/asottile/reorder-python-imports
      rev: v3.10.0
      hooks:
          - id: reorder-python-imports
